export const PATHS = {
  login: "/login",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  dashboard: "/dashboard",
  admin: "/admin",
  adminDashboard: "/admin/dashboard",
  adminStudents: "/admin/students",
  activate: "activate",
  adminStudentDetails: (id: string) => `/admin/students/${id}`,
  adminTeachers: "/admin/teachers",
  adminTeacherDetails: (id: string) => `/admin/teachers/${id}`,
  adminAcademic: "/admin/academic",
  adminAcademicYears: "/admin/academic?tab=years",
  adminAcademicGrades: "/admin/academic?tab=grades",
  adminAcademicSubjects: "/admin/academic?tab=subjects",
  adminAcademicCurriculum: "/admin/academic?tab=curriculum",
  adminAssignments: "/admin/assignments",
  adminAttendance: "/admin/attendance",
} as const